name: 'Build'
on:
  workflow_call:
    inputs:
      gitversion-config:
        description: 'Path to GitVersion configuration file'
        required: true
        type: string
      build_installer:
        description: 'Push the artifacts'
        default: false
        required: false
        type: boolean
      artifact_name_out:
        description: 'Name of the artifact'
        default: 'workflow-share'
        required: false
        type: string
      artifact_retention_days:
        description: 'retention days for the artifact'
        default: 5
        required: false
        type: number  
        
    outputs:
      MajorMinorPatch:
        value: ${{ jobs.build.outputs.MajorMinorPatch }}
      SemVer:
        value: ${{ jobs.build.outputs.SemVer }}
        
jobs:
  build:
    name: 'Build (Sub-Workflow)'
    runs-on: windows-latest
    outputs:
      MajorMinorPatch: ${{ steps.gitversion.outputs.MajorMinorPatch }}
      SemVer: ${{ steps.gitversion.outputs.SemVer }}
      
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: 'Setup MSBuild'
        uses: microsoft/setup-msbuild@v2

      - name: 'Setup GitVersion'
        uses: gittools/actions/gitversion/setup@v1.2.0
        with:
          versionSpec: '5.x'

      - name: 'GitVersion updateprojectfiles'
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v1.2.0
        with:
          useConfigFile: true
          configFilePath: ${{ inputs.gitversion-config }}
          additionalArguments: '/updateprojectfiles'

      - name: 'Build'
        run: |
          dotnet build MountSend.sln --configuration Release
          mkdir ./Output
          Copy-Item -Path ./MountSendLib/bin/Release/*.nupkg -Destination ./Output/
          Copy-Item -Path ./MountSend/bin/Release/* -Destination ./Output/ -Recurse -Force
          Get-ChildItem -Path ./Output/ -Recurse -Include *.pdb,*.exe.config,*.deps.json | Remove-Item -Force
          Rename-Item -Path ./Output/net8.0 -NewName MountSend-net8.0
          Rename-Item -Path ./Output/net48 -NewName MountSend-net48
        
      - name: 'Zip artifact archive'
        run: |
          cd ./Output
          7z a -tzip -sdel MountSend-net8.0.zip MountSend-net8.0/*
          rmdir MountSend-net8.0
          7z a -tzip -sdel MountSend-net48.zip MountSend-net48/*
          rmdir MountSend-net48
          
      - name: 'Upload source artifact'
        if: ${{ inputs.build_installer == true }}
        uses: actions/upload-artifact@v4.5.0
        with:
          name: ${{ inputs.artifact_name_out }}
          path: ./Output
          compression-level: 0
          retention-days: ${{ env.artifacts_retention_days }}
